lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Cross UI Kit
author:
  name: Purbohadi Utomo
  email: purbohadi.utomo@gmail.com

description: >
  A cross platform UI Kit for building cross platform applications using Flutter, React, and Vue.js.
  It is a collection of UI components and templates that can be used to create beautiful and responsive user interfaces.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: Cross UI Kit repository at GitHub
      icon: github
      url: "https://github.com/crossuikit/crossuikit"
    - title: CrossUIKit at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/crossuikit"
