lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
author:
  name: John Smith
  email: "john.smith@foobar.com"
minima:
  show_excerpts: true
